use customer_analysis;
select * from customer1 limit 20;


-- Q1: what is total revenue generated by male vs female
select gender, sum(purchase_amount) as total_revenu
from customer1
group by gender order by gender ;

-- Q2: Which customer used a discount but still spent more than average purchase amount 
select customer_id,purchase_amount
from customer1
where discount_applied="Yes" and purchase_amount< (select avg(purchase_amount) from customer1);

select avg(purchase_amount) from customer1;

-- Q3: Which are the five products with the highest average review rating 
select item_purchased,round(avg(review_rating),2)
from customer1
group by item_purchased
order by avg(review_rating) desc 
limit 5;

-- Q4: Compare the average purchase amounts between standard and expressive shipping 
select shipping_type,avg(purchase_amount)
from customer1
where shipping_type in ('Standard','Express')
group by shipping_type;

-- Q5: Do subscribed  customers spend more ? Compare average spend and total revenue between subscribers and non subscribers 
select subscription_status, count(customer_id) as Total_customer,round(avg(purchase_amount),2) as Average, round(sum(purchase_amount),2) as Revenue
from customer1
group by subscription_status

-- Q6: Which 5 products have the highest percentage of purchase with discount applied 


